title: I'm Matt Gallion
description: > # this means to ignore newlines until "baseurl:"
  I'm an Electrical Engineer specializing in control circuit design, PCB layout, and testing.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Matt Gallion # add your name
author-img: matt-gallion.jpg # add your photo
about-author: I'm an Electrical Engineer specializing in control circuit design, PCB layout, and testing. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: mattgallion # add your Github handle
social-linkedin: mattgallionde # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
